### ISSUE TITLE
validating hl7 fhir schema - failure

### ISSUE THREAD

**Issue by richbraman** [ssilverman/snowy-json#1]
I am looking at https://www.hl7.org/fhir/fhir.schema.json.zip through the lens of your product to see if I can use snowy to validate json payloads against this schema.  the schema purports to be conformant to draft 06. when I run your linter against it, it fails immediately.  I was able to get a part of the schema https://www.hl7.org/fhir/patient.schema.json.html to pass the linter, but I can't validate the json against it because of missing $ref(s). I am new to json schemas so I have another question regarding validation of json.  fhir is organized according to resources.  the full schema consist of all the resources in the data model.  if I validate a JSON payload representing the Patient resource, would I run it against the whole schema?  thanks in advance for the education.

**Comment by ssilverman** [comment]
Are you able to provide the JSON instance (or equivalent example if what you've got is confidential) you're trying to validate? Then I can test what you're seeing and provide some guidance.

**Comment by ssilverman** [comment]
It looks like the schema from that second link, when trying to follow references to do validation of subschemas, can't find whatever those references are referring to. For example, it needs to know where `Element.schema.json` and `Narrative.schema.json` are. It's possible to tell the validator where to find these files, but they need to exist first. You'd probably have to create them yourself (or from some other link on that site) by using the contents of the full schema.

I'd just validate against the whole schema, but note that it will have to check everything because of the "oneOf" at the root of the schema. That means "exactly one of must match, no more and no less". You could instead start from the whole schema and remove all the "definitions" parts that you don't need, for example every non-"Patient" child of "definitions" that isn't also needed by "Patient".

**Comment by ssilverman** [comment]
I'll also add: The linter just checks for some rudimentary things. It doesn't currently try to follow any references or links. In fact, the validator doesn't either until the references are actually followed as the instance is processed.

**Comment by ssilverman** [comment]
See the new https://github.com/ssilverman/snowy-json/commit/e207f2fff7526e7cdbdc94630262ae71d4a49a64 for a clarifying paragraph that explains that potential problems shown by the linter does not mean the schema won't work.

**Comment by ssilverman** [comment]
I played with this some more and was able to get a sample Patient (https://www.hl7.org/fhir/patient-example-a.json.html) validating. I had to do a couple things, though.

First, I had to add the following value to the "definitions" section of the Patient schema. I think the fact this is missing (or referenced to a local value) is a mistake.
```json
    "boolean": {
      "pattern": "^true|false$",
      "type": "boolean",
      "description": "Value of \"true\" or \"false\""
    },
```

Next, I inserted some known URLs in `Main.main` at the appropriate spot. Notice the new `knownURLs` argument to `Validator.validate`.
```java
    Map<URI, URL> knownURLs = new HashMap<>();
    URL url = new URL("file:path-to/fhir.schema.json");
    knownURLs.put(schemaID.resolve("id.schema.json"), url);
    knownURLs.put(schemaID.resolve("Narrative.schema.json"), url);
    knownURLs.put(schemaID.resolve("Identifier.schema.json"), url);
    knownURLs.put(schemaID.resolve("HumanName.schema.json"), url);
    knownURLs.put(schemaID.resolve("Attachment.schema.json"), url);
    knownURLs.put(schemaID.resolve("CodeableConcept.schema.json"), url);
    knownURLs.put(schemaID.resolve("Reference.schema.json"), url);

    long time = System.currentTimeMillis();
    boolean result = Validator.validate(schema, instance, schemaID,
                                        Collections.emptyMap(), knownURLs,
                                        opts, null, errors);
    time = System.currentTimeMillis() - time;
    logger.info("Validation result: " + result + " (" + time/1000.0 + "s)");
```

Note that `path-to` part in the URL is some relative path (or absolute path if you like) to the full schema file.

This addition lets the validator know how to resolve any unknown references it encounters. To find these, I did a search for all references in the Patient schema that were not local. i.e. they consisted of more than just a URI fragment.

Also note that none of this is needed if you just validate against the whole schema.
