### ISSUE TITLE
Is there any maven repo to download it ?

### ISSUE THREAD

**Issue by borgogelli** [ssilverman/snowy-json#2]
Is there any maven repo to download it ?

**Comment by dadacafe** [comment]
I came to ask the same thing; Are there any plans for refactoring it as library that could be simply downloaded from maven central.

**Comment by ssilverman** [comment]
I’ll look into this when I have a chance.

@dadacafe did you just have a comment here or was it removed? Strange, I could have sworn one was here. (Sometimes I do strange things on GitHub when using my phone. I hope I didn’t delete it by mistake. Apologies if I did.)

**Comment by dadacafe** [comment]
> @dadacafe did you just have a comment here or was it removed? 

Well actually I had, but I decided to delete it and upvote borgogelli's post instead as mine didn't add any relevant info. :)

**Comment by ssilverman** [comment]
See https://search.maven.org/artifact/com.qindesign/snowy-json/0.14.0/jar for the first release.

**Comment by ssilverman** [comment]
It turns out that you can access any GitHub library via [jitpack.io](https://jitpack.io/) as well. See that site for more details. If I had known about that before I submitted to Maven Central, I would have used that instead.

**Comment by borgogelli** [comment]
Thank you
