### ISSUE TITLE
Disabling annotations and retrieving output JSON during JSON Schema Validator and Linter run

### ISSUE THREAD

**Issue by gameboyzone** [ssilverman/snowy-json#6]
Hello Snowy Authors / Contributors,

Few questions -

1. When running the following commands, how can I know the status of the JSON Schema Validator and JSON Schema Linter? When my Build pipeline runs these commands, I want to access only the output JSON string and nothing irrelevant from the console. 

**JSON Schema Validator command**: mvn compile exec:java@main -Dexec.args="schema.json instance.json"

`
Basic Output:
{
     "valid": true,
     "errors": []
}
`

**JSON Schema Linter command**: mvn compile exec:java@linter -Dexec.args="schema.json"

PS: Linter is a special case, it doesn't output anything if it passes. How can I tackle this Linter scenario?

2. When the above commands are run, can I pass any additional arguments to the command to disable displaying annotations? I searched the documentation and the Main.java in the actual source code and didn't see any flag which I can use to disable displaying annotations. 

`
Annotations:
{ 
     "annotations": [
     ]
}
`

3. Now assume I want to run multiple automated JSON Schema and Linter checks from the Maven Java application, how can I run these commands from within the application? Should I run the commands or use the API in the JAR to call methods? Some examples for both scenarios would help.

**Comment by ssilverman** [comment]
Thank you for using the library.

I built the programs as demonstrations of how to use the API; they're not designed to be full-featured. My suggestion is to include this library as a dependency and create your own wrapper with the features you need. Having said that, these are good suggestions and, if I have some time, might add some features to make these requests easier, including a few more examples.

Note that the program design is still in flux, although changes are slowing down. Upcoming are a few minor changes to how errors are collected.

**Comment by gameboyzone** [comment]
Where can i see your upcoming list of changes along with the description?

Secondly, my company is going to utilize your libraries for JSON Schema validation and Linter

**Comment by gameboyzone** [comment]
Few follow-up questions -

1. Where can i see your upcoming list of changes along with the description? We'll keep a tab on it. 

2. Secondly, my company is going to utilize your libraries for JSON Schema validation and JSON Schema Linter validation. We'll aim to write a wrapper for the output filtering, I believe we use a custom Java class, declare it under Maven plugin in pom.xml file. This custom Java class will call the Snowy Jar's Main and Linter Classes and pass the arguments. The output will be filtered by my wrapper class. Does that approach sound correct? 

3. Is the library going to support JSON Schema Draft 8 specification?

**Comment by luposlip** [comment]
@gameboyzone just interrupting here:
3. `draft-08` is now known as `2019-09`, and is supported.

**Comment by ssilverman** [comment]
@gameboyzone I’m not completely happy with how much detail the errors contain and how they need to be filtered. I’m still cogitating.

For your second question, I wouldn’t call those example programs, especially by calling them to parse their output. I’d duplicate what you need from them and use them in your own program. I’m curious, how are you calling them now? As a separate process or by directly calling their `main` methods?

@luposlip answered about Draft 8. It became Draft 2019-09, and Snow supports this.

**Comment by gameboyzone** [comment]
**Regarding your Question 2** -

Currently I'm calling the JSON Schema Validator and Linter using the Maven plugin commands. Are you referring to this - from my Java application, I should call the plugin's command and parse the output?

Or you saying from my Java application, I should import and initialize the com.qindesign.json.schema.Main class and call the main() method in it with the right arguments? Based on the string output received, filter it and just retrieve the validation status (true / false)?

**Comment by ssilverman** [comment]
That seems like a lot of work. I would just do what `Main` does in your own program and not call `Main.main()` itself. That's just an example program, and it's neither designed to be full-featured, nor designed to be called from another program in a clean way.

All you need to do is import the classes somehow, and then call them. For Maven, just add this dependency (choose whatever is the latest, currently, it's "0.15.0-SNAPSHOT"):
```xml
    <dependencies>
        <dependency>
            <groupId>com.qindesign</groupId>
            <artifactId>snowy-json</artifactId>
            <version>0.15.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
```

Other IDEs and other platforms and systems may not use Maven, so you'll need to use whatever they use for adding to a project.

Here's some example functions for use in your own program, if all you want to do is validate (using the GSON library (`JsonElement`)):
```java
  /**
   * Validates an instance against a schema. The schema needs a base URI, which
   * can be any unique identifier, for example its file or retrieval URL. This
   * parses the input via {@link JSON#parse(Reader)} and then calls
   * {@link #validate(JsonElement, URI, JsonElement)} with the
   * {@link JsonElement}s.
   *
   * @param schemaIn the schema input, a Reader
   * @param baseURI the schema's base URI
   * @param instanceIn the instance input, a Reader
   * @return the validation result.
   * @throws MalformedSchemaException if there was an error with the schema.
   */
  private boolean validate(Reader schemaIn, URI baseURI, Reader instanceIn)
      throws MalformedSchemaException {
    return validate(JSON.parse(schemaIn), baseURI, JSON.parse(instanceIn));
  }

  /**
   * Validates an instance against a schema. The schema needs a base URI, which
   * can be any unique identifier, for example its file or retrieval URL.
   *
   * @param schemaIn the schema
   * @param baseURI the schema's base URI
   * @param instanceIn the instance
   * @return the validation result.
   * @throws MalformedSchemaException if there was an error with the schema.
   */
  private boolean validate(JsonElement schema, URI baseURI, JsonElement instance)
      throws MalformedSchemaException {
    // No known IDs or URLs, and no options set
    Validator validator = new Validator(schema, new com.qindesign.net.URI(baseURI),
                                        null,  // knownIDs
                                        null,  // knownURLs
                                        null);  // options
    return validator.validate(instance,
                              null,  // annotations
                              null);  // errors
  }
```

**Comment by ssilverman** [comment]
Closing for now. Feel free to pose another question.
