### ISSUE TITLE
Unknown schema ID

### ISSUE THREAD

**Issue by luposlip** [ssilverman/snowy-json#7]
Using version `0.14.0`.

Getting the following error when trying to validate a JSON document with a JSON schema:

```
Execution error (MalformedSchemaException) at com.qindesign.json.schema.ValidatorContext/schemaError (ValidatorContext.java:963).
http://example.com/product.schema.json#/$schema: unknown schema ID
```

These are a couple of lines from the JSON schema:

```json
"$schema": "http://json-schema.org/draft/2019-09/
"$id": "http://example.com/product.schema.json"
```

I instantiate the `Validator` with the schema read via `JSON.parse` from a `File`, the `URI` for the schema via `URI.parse("http://example.com")`.

I've tried with different URLs passed to the `URI.parse("...")`, and with and without an `Options` instance - i.e. `AUTO_RESOLVE` set to both `true` and `false`.

The same error every time.

Any idea what I'm doing wrong?

**Comment by ssilverman** [comment]
The ID for the Draft 2019-09 schema is "https://json-schema.org/draft/2019-09/schema".

What you have for the value of $schema is unknown.

**Comment by luposlip** [comment]
My bad - thanks!
